features_dir: features
experiment_path: experiment.json
result_dir: result
luigi_dir: luigi
target_col: y
evaluator_flag: f1_macro
feature_importance_model_flag: lgbm_multi
num_class: 8
importance_flag: mean # mean, null_importance
null_importance_trials: 10
trainer_flag: down_sample_bagging # basic, down_sample_bagging
folds_generator_flag: stratified_group # kfold, group, stratified, stratified_group
group_kfolds_col: gameID # atbat_id, gameID
verbose_eval: 100
num_boost_round: 2000
early_stopping_rounds: 20
fold_num: 5
seed: 42
bagging_num: 5
base_class: 3 # downsampling target base class (int)
allow_less_than_base: True
drop_cols:
   # not in test
   - pitchType
   - speed
   - ballPositionLabel
   - ballX
   - ballY
   - dir
   - dist
   - battingType
   - isOuts